version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: finance-postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: finance-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres